const DEFAULT_SLIDE_SELECTOR = 'image-carousel';
const DEFAULT_HOLD_TIME = 5000;
const DEFAULT_TRANSITION_TIME = 500;

const DEFAULT_SLIDER_CONFIGURATION = {
	sliderSelector: DEFAULT_SLIDE_SELECTOR,
	holdTime: DEFAULT_HOLD_TIME,
	transitionTime: DEFAULT_TRANSITION_TIME,
};
